#define SETUP_MAIN_MENU_TITLE "C= PET Model"
#define SETUP_ESC_DEFAULT_DELAY_MS 4000

// #define SETUP_DISABLE_ADMINISTRATON_MENU
#define USE_ANSI

#define SETUP_ENABLE_WIFI_SETUP_OPTIONS                 1
#define SETUP_ENABLE_ADMINISTRATON_MENU                 1
#define SETUP_ADMINISTRATION_ENABLE_SETUP_FACTORY_RESET 1